# Uncomment the next line to define a global platform for your project
#platform :ios, ’10.0’

target 'Sharpr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sharpr
target 'Sharpr' do
	pod "DualSlideMenu"
end


  target 'SharprTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SharprUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
